### ISSUE TITLE
Post MVP Project specs

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#111] opened 2022-07-14 20:09 UTC

**Comment by sharon-rabang** [comment] 2022-09-12 20:25
Discussed with @extinah. Will close this duplicate of [Project Spec doc for lab.data.ca.gov #132](https://github.com/CA-Data/Open-Data-Portal/issues/132).

**Closed by sharon-rabang** 2022-09-12 20:25 UTC
