### ISSUE TITLE
UAT Fix: Organization and Topics pages - Filter

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#128] opened 2022-07-22 00:01 UTC
Issue: When resetting filters, the topic or organization that is selected also is unchecked. And when you go to select that item - you can't.

Fix: Don't allow reset filter to remove that criteria.

![image](https://user-images.githubusercontent.com/33840424/180334319-98e446f9-6dc2-44c7-b3e8-308ea1995ae9.png)

**Comment by sharon-rabang** [comment] 2022-07-26 16:08
@jon-grant-state-ca-gov Please let me know if you have any questions, and when it's ready for review. Thanks!

**Comment by sharon-rabang** [comment] 2022-08-10 18:29
@jon-grant-state-ca-gov Hi! Following up to see if you'll have the bandwidth to help with this one.

**Comment by jon-grant-state-ca-gov** [comment] 2022-09-07 18:24
@sharon-rabang I got the ok from my manager to work on this issue. I will update when the issue is resolved :)

**Comment by Greg-Watanabe** [comment] 2022-09-08 00:32
@sharon-rabang 
I merged with sandbox, you can review there:
https://sandbox.data.ca.gov/topic/datasets?q=&topic=economy-and-demographics

**Comment by sharon-rabang** [comment] 2022-09-08 14:50
@Greg-Watanabe Looks good, thanks! Please add to https://lab.data.ca.gov/ and let me know when it's ready for review.

**Comment by sharon-rabang** [comment] 2022-09-12 15:58
@Greg-Watanabe @jon-grant-state-ca-gov FYI - @hamiltonryan can review the changes in https://lab.data.ca.gov/ while I'm OOO. 

Please tag Ryan so he can let you know if there's a concern, or if this issue is complete and closed. 
Ryan, please also go to the [ODP Project Board](https://github.com/orgs/CA-Data/projects/1 ) and move this issue's card to "Done - In Production". Thanks!

**Comment by Greg-Watanabe** [comment] 2022-09-12 19:03
@sharon-rabang  @hamiltonryan 
This is now on lab
https://lab.data.ca.gov/topic/datasets?q=&topic=natural-resources

**Comment by sharon-rabang** [comment] 2022-09-12 19:05
@Greg-Watanabe @hamiltonryan Review completed. Closing this issue, thanks!

**Closed by sharon-rabang** 2022-09-12 19:05 UTC
Labels: Engineering

**Comment by jon-grant-state-ca-gov** [comment] 2022-10-11 07:14
Hi Sharon,

The last I have heard from Selvi is that I am to be working on our engineering team projects. I will let the Open Data team know if I hear anything differently though 🙂

Thanks,
Jon
________________________________

**Comment by sharon-rabang** [comment] 2022-10-11 14:06
@jon-grant-state-ca-gov Hi! Thanks for checking in! This task has actually completed and closed.
